config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmlend
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book =Book.new(book_params)
      if @book.save
      flash[:notice] ="Book was successfully created !"
      redirect_to book_path(@book.id)
      else
     @books = Book.all
     flash.now[:notice] = "error"
     render :index
      end
  end

  def index
      @books = Book.all
      @book =Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)

      flash[:notice] ="Book was successfully updated !"
      redirect_to book_path(@book.id)
    else
     flash.now[:notice] = "error"
     render :edit
    end
  end


  def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!--<h1>Books#edit</h1>-->
<!--<p>Find me in app/views/books/edit.html.erb</p>-->


<h3>Editing Book</h3>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
  <%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<div>
<!--https://html-coding.co.jp/annex/dictionary/html/tr/-->
<h1>Books</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <table>
   <tr>
   <th>Title</th>
   <th>Body</th>
   </tr>
<% @books.each do |book| %>
 <tr>
   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td><%= link_to 'Show', book_path(book) %></td>
   <td><%= link_to 'Edit', edit_book_path(book) %></td>
   <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you ok？" %></td>
 </tr>
<% end %>
</table>
</div>

<h3>New book</h3>
<%= form_with model: @book do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>

  <h5>Body</h5>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<!--<h1>Books#new</h1>-->
<!--<p>Find me in app/views/books/new.html.erb</p>-->

<!--<h3>New book</h3>-->
<!--<%#= form_with model: Book.new do |f| %>-->
<!--  <h5>Title</h5>-->
<!--  <%#= f.text_field :title %>-->

<!--  <h5>Body</h5>-->
<!--  <%#= f.text_area :body %>-->

<!--  <%#= f.submit 'Create Book' %>-->
<!--<%# end %>-->

app/views/books/show.html.erb
<!--<h1>Books#show</h1>-->
<!--<p>Find me in app/views/books/show.html.erb</p>-->


<h5>Title:</h5>
<p><%= @book.title %></p>

<h5>Body:</h5>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<!--<h1>Homes#top</h1>-->
<!--<p>Find me in app/views/homes/top.html.erb</p>-->

<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to 'start', books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div>
    <%= flash[:notice] %>
   </div>
    <%= yield %>
    </body>
</html>